MAKEFILE_DIR=/home/John/MyDrums/test
PROJECT_DIR=/home/John/MyDrums
TEST_DIR=/home/John/MyDrums/test

CPPUTEST_HOME=/home/John/cpputest
#SRC_DIRS=$(PROJECT_DIR)/src
INCLUDE_DIRS=$(PROJECT_DIR)/src
INCLUDE_DIRS+=$(CPPUTEST_HOME)/include
TEST_SRC_DIRS=$(TEST_DIR)
TEST_TARGET=test_runner

#run MakefileWorker.mk with the variables defined here
include $(CPPUTEST_HOME)/build/MakefileWorker.mk